### ISSUE TITLE
hostname 获取不正常

### ISSUE THREAD

**Issue by MBRjun** [MBRjun/MBRjun-Blog#13]
### Environment
OS: Proxmox VE 7.3-3(Debian 11.6)
Kernel: Linux 6.1.0-1-pve
Program version: ``39bab46a39fce053283b4d00bdffc14c7c03780f``

---

### What happened 
Got an error "``Unknown command verb hostname.``" when generating build info.

---

### To replicate

1. Run ``make genver``

---

### Screenshots

![9E417A74-8B6B-4129-AC8A-6D824B4F4625](https://user-images.githubusercontent.com/55020690/216653428-94754905-c6c1-4810-9e80-70151e6d6de5.jpeg)

**Comment by Yang-Fly** [comment]
@MBRjun 非常好 issue, 爱来自 undefined
