### ISSUE TITLE
求编译rtl8186网卡驱动的esxi

### ISSUE THREAD

**Issue by JackHe98** [MBRjun/MBRjun-Blog#20]
大佬您好，我按照您的博客编译含有rtl8186网卡驱动的esxi，但是一直失败，我想要直接下载您的镜像，可是失败了，不知道您有空可否传一份给我，非常感谢！

**Comment by MBRjun** [comment]
我那个封装的有 bug，8168 驱动只在 ESXi 6 稳定，建议还是放弃 ESXi 7/8 或者换网卡

_Originally posted by @MBRjun in https://github.com/MBRjun/MBRjun-Blog/discussions/19#discussioncomment-4984027_

**Comment by JackHe98** [comment]
好吧，谢谢你！
